site_name: 朝闻道家庭投资基金
theme:
  name: material
  language: zh
nav:
  - 首页: index.md
  - 投资品种:
    - 股票:
      - 腾讯控股: assets/tencent.md
      - 小米集团: assets/xiaomi.md
      - 贵州茅台: assets/maotai.md
      - 安克创新: assets/ankr.md
      - 伯克希尔-哈撒韦: assets/berkshire.md
      - 名创优品: assets/miniso.md
      - 泡泡玛特: assets/popmart.md
      - 瑞幸咖啡: assets/luckin.md
      - 拼多多: assets/pinduoduo.md
    - 区块链:
      - BTC: assets/btc.md
      - ETH: assets/eth.md
      - SOL: assets/sol.md
  - 定期报告:
    - 2025年:
      - W7周报-关于大S去世后讨论的思考: reports/2025/report-2025W7.md
    - 2024年:
      - W1周报: reports/2024/report-2024W1.md
      - W2周报: reports/2024/report-2024W2.md
      - W3周报: reports/2024/report-2024W3.md
      - W7周报: reports/2024/report-2024W7.md
      - W9周报: reports/2024/report-2024W9.md
      - W10周报: reports/2024/report-2024W10.md
      - W11周报: reports/2024/report-2024W11.md
      - W14周报: reports/2024/report-2024W14.md
      - W18周报: reports/2024/report-2024W18.md
      - W19周报: reports/2024/report-2024W19.md
      - W20周报: reports/2024/report-2024W20.md
      - W21周报: reports/2024/report-2024W21.md
      - W22周报-分红、讲故事与赌博: reports/2024/report-2024W22.md
      - 半年报-投资需要学习什么知识？: reports/2024/report-2024H1.md
      - W34周报-游戏产业的价值是什么？: reports/2024/report-2024W34.md
      - W38周报-直觉投资者、被动投资者和主动投资者: reports/2024/report-2024W38.md
      - W39周报-从名创优品收购永辉超市聊企业家精神: reports/2024/report-2024W39.md
      - W44周报-牛市与赌场: reports/2024/report-2024W44.md
      - 年报-买股票的三层逻辑: reports/2024/report-2024.md
    - 2023年:
      - 半年报: reports/2023/report-2023H1.md
      - W49周报: reports/2023/report-2023W49.md
      - W50周报: reports/2023/report-2023W50.md
      - W51周报: reports/2023/report-2023W51.md
      - W52周报: reports/2023/report-2023W52.md
      - 年报: reports/2023/report-2023.md
    - 2022年:
      - 年报: reports/2022/report-2022.md
    - 2021年:
      - 年报: reports/2021/report-2021.md
    - 2020年:
      - 1季报: reports/2020/report-2020Q1.md
      - 2季报: reports/2020/report-2020Q2.md
      - 3季报: reports/2020/report-2020Q3.md
      - 年报: reports/2020/report-2020.md
    - 2019年:
      - 1月报: reports/2019/report-201901.md
      - 2月报: reports/2019/report-201902.md
      - 3月报: reports/2019/report-201903.md
      - 4月报: reports/2019/report-201904.md
      - 5月报: reports/2019/report-201905.md
      - 6月报: reports/2019/report-201906.md
      - 7月报: reports/2019/report-201907.md
      - 8月报: reports/2019/report-201908.md
      - 9月报: reports/2019/report-201909.md
      - 10月报: reports/2019/report-201910.md
      - 11月报: reports/2019/report-201911.md
      - 年报: reports/2019/report-2019.md
    - 2018年:
      - 1月报: reports/2018/report-201801.md
      - 2月报: reports/2018/report-201802.md
      - 3月报: reports/2018/report-201803.md
      - 4月报: reports/2018/report-201804.md
      - 5月报: reports/2018/report-201805.md
      - 6月报: reports/2018/report-201806.md
      - 7月报: reports/2018/report-201807.md
      - 8月报: reports/2018/report-201808.md
      - 9月报: reports/2018/report-201809.md
      - 10月报: reports/2018/report-201810.md
      - 11月报: reports/2018/report-201811.md
      - 年报: reports/2018/report-2018.md
    - 2017年:
      - 1月报: reports/2017/report-201701.md
      - 2月报: reports/2017/report-201702.md
      - 3月报: reports/2017/report-201703.md
      - 4月报: reports/2017/report-201704.md
      - 5月报: reports/2017/report-201705.md
      - 6月报: reports/2017/report-201706.md
      - 7月报: reports/2017/report-201707.md
      - 8月报: reports/2017/report-201708.md
      - 9月报: reports/2017/report-201709.md
      - 10月报: reports/2017/report-201710.md
      - 11月报: reports/2017/report-201711.md
      - 年报: reports/2017/report-2017.md
    - 2016年:
      - 年报: reports/2016/report-2016.md
  - 操作记录:
    - 2025年: logs/log-2025.md
    - 2024年: logs/log-2024.md
    

